name: akilli_kampus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

    #firebase
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.2
  firebase_messaging: ^14.6.5
  firebase_remote_config: ^4.2.5

  #Animation
  simple_animations: ^4.0.1
  supercharged: ^2.1.1
  animated_text_kit: ^4.2.2
  #animate_do: ^3.0.2
  page_transition: ^2.0.9


  #State Managment
  mobx_codegen: ^2.3.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  # language
  easy_localization: ^3.0.2

  #Svg Picture
  flutter_svg: ^1.0.0

  #audio
  assets_audio_player: ^3.0.6

  #imageSlider
  carousel_slider: ^4.2.1
  #Shimmer
  shimmer: ^3.0.0
  #Page Indicator
  smooth_page_indicator: ^1.1.0
  #Lucky Wheel
  flutter_fortune_wheel: ^1.2.1
  #lottie
  lottie: ^2.4.0
  #time
  flutter_native_timezone: ^2.0.0
  #http
  http: ^0.13.0
  json_annotation: ^4.8.1
  #Network
  connectivity_plus: ^4.0.1
  #webview_flutter
  webview_flutter: ^3.0.0
  #url navigator
  url_launcher: ^6.0.0


  cached_network_image: ^3.2.3
  package_info_plus: ^4.1.0
  palette_generator: ^0.3.3+2

  #user_messaging_platform: ^1.2.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  webview_flutter: ^3.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.13.1
  qr_code_scanner: ^1.0.1

dependency_overrides:
  test_api: 0.4.18

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/animation/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
