// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEjGL-HbhR1hitPjRleC8JscK1qFO5VH0',
    appId: '1:496963894526:web:6971e39daa2c029d5479af',
    messagingSenderId: '496963894526',
    projectId: 'akillikampus-4ee8c',
    authDomain: 'akillikampus-4ee8c.firebaseapp.com',
    storageBucket: 'akillikampus-4ee8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ09GUrzhd_6EXynwZpogIdYA3X00oDc4',
    appId: '1:496963894526:android:52bbb5332840fe2f5479af',
    messagingSenderId: '496963894526',
    projectId: 'akillikampus-4ee8c',
    storageBucket: 'akillikampus-4ee8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPOBLG7FyidqpE7y43tyHQJxZJvzpyrjI',
    appId: '1:496963894526:ios:fe58ad83ed01be675479af',
    messagingSenderId: '496963894526',
    projectId: 'akillikampus-4ee8c',
    storageBucket: 'akillikampus-4ee8c.appspot.com',
    iosBundleId: 'com.example.akilliKampus',
  );
}
